stages:         
  - test
  - build
  - deploy

variables:
  REGISTRY_URL: registry.gitlab.com
  PROJECT_NAME: product
  PROJECT_DIR: product-service
  NAMESPACE: production
  TAG: 0.0.1 

unit-test:
  stage: test
  image: gradle:6.9-jdk11
  script:
    - echo 
    - cd $PROJECT_DIR
    - gradle test

build-job:       
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY_URL\":{\"username\":\"$REGISTRY_USERNAME\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "build docker image"
    - echo $REGISTRY_URL
    - echo $REGISTRY_USERNAME
    - /kaniko/executor --insecure --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination $REGISTRY_URL/sinwoo1225/greenmarket/$PROJECT_DIR:$TAG
  only:
    - /^realese-.*/
    - web
    
deploy-job:      
  stage: deploy 
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context sinwoo1225/Greenmarket:kas
  script:
    - kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE
    - kubectl apply -f deployments/greenmarket-${PROJECT_NAME}-deployment.yaml
    - echo "Application successfully deployed."
  only:
    - /^realese-.*/
    - web
