version: '3.8'

services:
  redis:
    image: sameersbn/redis:latest
    container_name: greenmarket-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    container_name: greenmarket-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=siru@dev1
    platform: linux/x86_64


  product-service:
    image: product-service:0.0.1
    container_name: greenmarket-product-service
    ports:
      - "8110:8110"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  
  user-service:
    image: greenmarket-user-app:0.0.1
    container_name: greenmarket-user-service
    ports:
      - "8130:8130"

  chat-service:
    image: greenmarket-chat-app:0.0.1
    container_name: greenmarket-chat-service
    ports:
      - "8140:8140"