server:
  port: 8150

# 스프링 설정
spring:
  devtools:
    livereload:
      enabled: true

  # 데이터베이스 세팅
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# 업로드 파일 설정
file-resource:
    product-image-url: /resources/images/product/
    profile-image-url: /resources/images/profile/
    product-image-save-path: src/main/resources/images/product/
    profile-image-save-path: src/main/resources/images/profile/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace