server:
  port: 8110
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force:  true

# 스프링 설정
spring:
  devtools:
    livereload:
      enabled: true

  # 데이터베이스 세팅
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  sql:
    init:
      data-locations: classpath*:h2/data.sql
      mode: embedded

# jwt 설정
jwt:
  secret: sd0dfjnl!@123:23090ejasd1!@123Ko)9sdkf{}s*56&*27fnvpPxz0tamxzz.sf!@93a6nzlk9e2ro4&sa78df7jxnmgl
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace