# ??? ??
spring:
  devtools:
    livereload:
      enabled: true

# jwt ??
jwt:
  secret: sd0dfjnl!@123:23090ejasd1!@123Ko)9sdkf{}s*56&*27fnvpPxz0tamxzz.sf!@93a6nzlk9e2ro4&sa78df7jxnmgl
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800